### PR TITLE
fix executing gui as root in wayland

### PR DESCRIPTION
**Pull request by dzshn**
guh

### CODE REVIEW

**Comment by Vendicated** [comment]
Isn't this just a lack of proper wayland support in sudo and doas? I just tested and sudo (by default) preserves DISPLAY but not WAYLAND_DISPLAY. You can configure both sudo and doas to keep more environment variables so you could add those there

**Comment by Vendicated** [comment]
oh I think this is because Xorg sessions run as root, whereas wayland usually runs as normal user?

**Comment by Vendicated** [comment]
(I don't mind adding this, I'm just curious since this seems like an oversight in sudo/doas)

**Comment by dzshn** [comment]
> oh I think this is because Xorg sessions run as root, whereas wayland usually runs as normal user?

basically this, but also `WAYLAND_DISPLAY` isn't the full socket path so it has to be set to `$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY` (which also only works for root, because root is the only user who also has permission to read anything in another user's `XDG_RUNTIME_DIR`)

**Pull request merged**
